// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZimbabweTenderAPI.Data;

#nullable disable

namespace ZimbabweTenderAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.AwardNoticeAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AwardNoticeId")
                        .HasColumnType("int");

                    b.Property<string>("AwardNoticeNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AwardNoticeId");

                    b.HasIndex("AwardNoticeNumber", "ChangeDate");

                    b.ToTable("AwardNoticeAuditLogs");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.AwardNoticeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AwardDate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AwardNoticeNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AwardTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Awardee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ContractValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DetailsUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastScrapedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ParsedAwardDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TenderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AwardNoticeNumber")
                        .IsUnique();

                    b.HasIndex("TenderId");

                    b.ToTable("AwardNotices");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.ClosedTenderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AwardNoticeId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DetailsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastScrapedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("ProcuringEntity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Scope")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AwardNoticeId");

                    b.HasIndex("ClosingDate");

                    b.HasIndex("ReferenceNumber");

                    b.HasIndex("TenderId")
                        .IsUnique();

                    b.ToTable("ClosedTenders");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.LiveTenderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryCodes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DetailsUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastScrapedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MovedToClosed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MovedToClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("ProcuringEntity")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClosingDate");

                    b.HasIndex("ProcuringEntity");

                    b.HasIndex("ReferenceNumber");

                    b.HasIndex("TenderId")
                        .IsUnique();

                    b.ToTable("LiveTenders");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.ProcurementPlanAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcurementPlanId")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcurementPlanId", "ChangeDate");

                    b.ToTable("ProcurementPlanAuditLogs");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.ProcurementPlanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastScrapedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcuringEntity")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalEstimatedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ViewAppUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProcuringEntity", "Year")
                        .IsUnique();

                    b.ToTable("ProcurementPlans");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.ProcurementPlanItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AwardNoticeDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BidClosingDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClassOfProcurement")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractSigningDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CycleDays")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EoiClosingDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EoiPublicationDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSupplement")
                        .HasColumnType("bit");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LeadTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObjectCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ParsedAwardNoticeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ParsedBidClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ParsedContractSigningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ParsedTenderPublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PmoEndUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProcurementMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProcurementPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RefNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceOfFunds")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Spoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenderPublicationDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitOfMeasurement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProcurementPlanId", "RefNo");

                    b.ToTable("ProcurementPlanItems");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 455, DateTimeKind.Utc).AddTicks(1208),
                            CreatedBy = "System",
                            Description = "Full system access and administrative privileges",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 455, DateTimeKind.Utc).AddTicks(1214),
                            CreatedBy = "System",
                            Description = "Read-only access to public data",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Guest"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 455, DateTimeKind.Utc).AddTicks(1216),
                            CreatedBy = "System",
                            Description = "Supervisory access with approval permissions",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 455, DateTimeKind.Utc).AddTicks(1219),
                            CreatedBy = "System",
                            Description = "Human Resources access",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 455, DateTimeKind.Utc).AddTicks(1221),
                            CreatedBy = "System",
                            Description = "Project management access",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "ProjectManager"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 455, DateTimeKind.Utc).AddTicks(1223),
                            CreatedBy = "System",
                            Description = "Standard employee access",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 455, DateTimeKind.Utc).AddTicks(1225),
                            CreatedBy = "System",
                            Description = "Development team access",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Development"
                        });
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.ScrapingJobHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemsAdded")
                        .HasColumnType("int");

                    b.Property<int>("ItemsFailed")
                        .HasColumnType("int");

                    b.Property<int>("ItemsProcessed")
                        .HasColumnType("int");

                    b.Property<int>("ItemsUpdated")
                        .HasColumnType("int");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("JobType", "StartTime");

                    b.ToTable("ScrapingJobHistory");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.SystemConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemConfigurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Scraping",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2292),
                            CreatedBy = "System",
                            Description = "Enable/disable automatic scraping",
                            IsDeleted = false,
                            Key = "ScrapingEnabled",
                            Value = "true"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Scraping",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2298),
                            CreatedBy = "System",
                            Description = "Interval between automatic scraping jobs in minutes",
                            IsDeleted = false,
                            Key = "ScrapingIntervalMinutes",
                            Value = "60"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Scraping",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2301),
                            CreatedBy = "System",
                            Description = "Maximum number of concurrent scraping operations",
                            IsDeleted = false,
                            Key = "MaxConcurrentScrapes",
                            Value = "3"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Data",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2303),
                            CreatedBy = "System",
                            Description = "Number of days to retain closed tenders in database",
                            IsDeleted = false,
                            Key = "RetentionDaysClosedTenders",
                            Value = "365"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Email",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2306),
                            CreatedBy = "System",
                            Description = "Enable/disable email notifications",
                            IsDeleted = false,
                            Key = "EmailNotificationsEnabled",
                            Value = "false"
                        });
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.SystemSettingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "BackgroundJobs",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2355),
                            CreatedBy = "System",
                            Description = "Enable/disable live tenders sync job",
                            IsDeleted = false,
                            Key = "BackgroundJobs:LiveTendersSync:Enabled",
                            Value = "true"
                        },
                        new
                        {
                            Id = 2,
                            Category = "BackgroundJobs",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2357),
                            CreatedBy = "System",
                            Description = "Live tenders sync interval in hours (0.0833 = 5 minutes)",
                            IsDeleted = false,
                            Key = "BackgroundJobs:LiveTendersSync:IntervalHours",
                            Value = "0.0833"
                        },
                        new
                        {
                            Id = 3,
                            Category = "BackgroundJobs",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2359),
                            CreatedBy = "System",
                            Description = "Enable/disable closed tenders sync job",
                            IsDeleted = false,
                            Key = "BackgroundJobs:ClosedTendersSync:Enabled",
                            Value = "true"
                        },
                        new
                        {
                            Id = 4,
                            Category = "BackgroundJobs",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2361),
                            CreatedBy = "System",
                            Description = "Closed tenders sync interval in hours",
                            IsDeleted = false,
                            Key = "BackgroundJobs:ClosedTendersSync:IntervalHours",
                            Value = "24"
                        },
                        new
                        {
                            Id = 5,
                            Category = "BackgroundJobs",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2363),
                            CreatedBy = "System",
                            Description = "Hour to run closed tenders sync (24-hour format)",
                            IsDeleted = false,
                            Key = "BackgroundJobs:ClosedTendersSync:RunAtHour",
                            Value = "3"
                        },
                        new
                        {
                            Id = 6,
                            Category = "BackgroundJobs",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2365),
                            CreatedBy = "System",
                            Description = "Enable/disable award notices sync job",
                            IsDeleted = false,
                            Key = "BackgroundJobs:AwardNoticesSync:Enabled",
                            Value = "true"
                        },
                        new
                        {
                            Id = 7,
                            Category = "BackgroundJobs",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2368),
                            CreatedBy = "System",
                            Description = "Award notices sync interval in hours",
                            IsDeleted = false,
                            Key = "BackgroundJobs:AwardNoticesSync:IntervalHours",
                            Value = "24"
                        },
                        new
                        {
                            Id = 8,
                            Category = "BackgroundJobs",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2496),
                            CreatedBy = "System",
                            Description = "Hour to run award notices sync (24-hour format)",
                            IsDeleted = false,
                            Key = "BackgroundJobs:AwardNoticesSync:RunAtHour",
                            Value = "2"
                        },
                        new
                        {
                            Id = 9,
                            Category = "BackgroundJobs",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2498),
                            CreatedBy = "System",
                            Description = "Enable/disable procurement plans sync job",
                            IsDeleted = false,
                            Key = "BackgroundJobs:ProcurementPlansSync:Enabled",
                            Value = "true"
                        },
                        new
                        {
                            Id = 10,
                            Category = "BackgroundJobs",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2500),
                            CreatedBy = "System",
                            Description = "Procurement plans sync interval in hours (168 = weekly)",
                            IsDeleted = false,
                            Key = "BackgroundJobs:ProcurementPlansSync:IntervalHours",
                            Value = "168"
                        },
                        new
                        {
                            Id = 11,
                            Category = "BackgroundJobs",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2501),
                            CreatedBy = "System",
                            Description = "Hour to run procurement plans sync (24-hour format)",
                            IsDeleted = false,
                            Key = "BackgroundJobs:ProcurementPlansSync:RunAtHour",
                            Value = "4"
                        },
                        new
                        {
                            Id = 12,
                            Category = "BackgroundJobs",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2503),
                            CreatedBy = "System",
                            Description = "Enable/disable verify and move tenders job",
                            IsDeleted = false,
                            Key = "BackgroundJobs:VerifyAndMoveTenders:Enabled",
                            Value = "true"
                        },
                        new
                        {
                            Id = 13,
                            Category = "BackgroundJobs",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2506),
                            CreatedBy = "System",
                            Description = "Verify and move interval in hours",
                            IsDeleted = false,
                            Key = "BackgroundJobs:VerifyAndMoveTenders:IntervalHours",
                            Value = "6"
                        },
                        new
                        {
                            Id = 14,
                            Category = "JWT",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2507),
                            CreatedBy = "System",
                            Description = "JWT token expiration time in minutes (1440 = 24 hours)",
                            IsDeleted = false,
                            Key = "JWT:ExpirationMinutes",
                            Value = "1440"
                        },
                        new
                        {
                            Id = 15,
                            Category = "JWT",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2509),
                            CreatedBy = "System",
                            Description = "Refresh token expiration in days",
                            IsDeleted = false,
                            Key = "JWT:RefreshTokenExpirationDays",
                            Value = "7"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Gemini",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2511),
                            CreatedBy = "System",
                            Description = "Gemini AI model to use",
                            IsDeleted = false,
                            Key = "Gemini:Model",
                            Value = "gemini-2.0-flash-exp"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Gemini",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2512),
                            CreatedBy = "System",
                            Description = "Gemini AI temperature (0.0-1.0)",
                            IsDeleted = false,
                            Key = "Gemini:Temperature",
                            Value = "0.7"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Gemini",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2515),
                            CreatedBy = "System",
                            Description = "Maximum tokens for Gemini responses",
                            IsDeleted = false,
                            Key = "Gemini:MaxTokens",
                            Value = "8000"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Gemini",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2517),
                            CreatedBy = "System",
                            Description = "Enable/disable Gemini AI features",
                            IsDeleted = false,
                            Key = "Gemini:Enabled",
                            Value = "true"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Scraping",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2518),
                            CreatedBy = "System",
                            Description = "Number of items to process in each batch",
                            IsDeleted = false,
                            Key = "Scraping:BatchSize",
                            Value = "100"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Scraping",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2520),
                            CreatedBy = "System",
                            Description = "HTTP request timeout in seconds",
                            IsDeleted = false,
                            Key = "Scraping:TimeoutSeconds",
                            Value = "30"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Scraping",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2522),
                            CreatedBy = "System",
                            Description = "Number of retry attempts for failed requests",
                            IsDeleted = false,
                            Key = "Scraping:RetryAttempts",
                            Value = "3"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Scraping",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2524),
                            CreatedBy = "System",
                            Description = "Delay between scraping requests in milliseconds",
                            IsDeleted = false,
                            Key = "Scraping:DelayBetweenRequestsMs",
                            Value = "500"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Pagination",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2525),
                            CreatedBy = "System",
                            Description = "Default number of items per page",
                            IsDeleted = false,
                            Key = "Pagination:DefaultPageSize",
                            Value = "20"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Pagination",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2527),
                            CreatedBy = "System",
                            Description = "Maximum allowed page size",
                            IsDeleted = false,
                            Key = "Pagination:MaxPageSize",
                            Value = "100"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Analytics",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2529),
                            CreatedBy = "System",
                            Description = "Default days to look back for analytics",
                            IsDeleted = false,
                            Key = "Analytics:DefaultDaysBack",
                            Value = "90"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Analytics",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2530),
                            CreatedBy = "System",
                            Description = "Minimum confidence score for recommendations",
                            IsDeleted = false,
                            Key = "Analytics:MinConfidenceScore",
                            Value = "60"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Analytics",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2532),
                            CreatedBy = "System",
                            Description = "Maximum number of opportunities to return",
                            IsDeleted = false,
                            Key = "Analytics:MaxOpportunities",
                            Value = "50"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Logging",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2534),
                            CreatedBy = "System",
                            Description = "Enable logging to files",
                            IsDeleted = false,
                            Key = "Logging:EnableFileLogging",
                            Value = "true"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Logging",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2535),
                            CreatedBy = "System",
                            Description = "Directory path for log files",
                            IsDeleted = false,
                            Key = "Logging:LogPath",
                            Value = "C:/Temp"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Logging",
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2537),
                            CreatedBy = "System",
                            Description = "Number of days to keep log files",
                            IsDeleted = false,
                            Key = "Logging:RetentionDays",
                            Value = "30"
                        });
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.TenderApprovalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovalStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApproverComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApproverUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousApprovalId")
                        .HasColumnType("int");

                    b.Property<string>("RequestDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TenderId")
                        .HasColumnType("int");

                    b.Property<string>("TenderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatus");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("PreviousApprovalId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("TenderId", "TenderType");

                    b.ToTable("TenderApprovals");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.TenderAssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<string>("AssignmentInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TenderId")
                        .HasColumnType("int");

                    b.Property<string>("TenderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("TenderId", "AssignedToUserId");

                    b.ToTable("TenderAssignments");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.TenderAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClosedTenderId")
                        .HasColumnType("int");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("LiveTenderId")
                        .HasColumnType("int");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ClosedTenderId");

                    b.HasIndex("LiveTenderId");

                    b.HasIndex("TenderId", "ChangeDate");

                    b.ToTable("TenderAuditLogs");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.TenderChecklistItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CompletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TenderId")
                        .HasColumnType("int");

                    b.Property<string>("TenderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("TenderId", "TenderType");

                    b.ToTable("TenderChecklistItems");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.TenderDocumentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLatestVersion")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TenderId")
                        .HasColumnType("int");

                    b.Property<string>("TenderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("TenderId", "TenderType");

                    b.ToTable("TenderDocuments");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.UserAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ChangeDate");

                    b.ToTable("UserAuditLogs");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastLoginIP")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(1096),
                            CreatedBy = "System",
                            Email = "admin@tendersystem.com",
                            EmailConfirmed = true,
                            FailedLoginAttempts = 0,
                            FirstName = "System",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Administrator",
                            PasswordHash = "$2a$11$jxU2ZPd6q1hqGFn4xbozTeGmH5wqunZOn1M06UiPwOq1yaW3.sq7u",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.UserRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2160),
                            AssignedBy = "System",
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2163),
                            AssignedBy = "System",
                            RoleId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AssignedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2165),
                            AssignedBy = "System",
                            RoleId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            AssignedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2167),
                            AssignedBy = "System",
                            RoleId = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            AssignedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2168),
                            AssignedBy = "System",
                            RoleId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            AssignedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2169),
                            AssignedBy = "System",
                            RoleId = 6,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            AssignedAt = new DateTime(2026, 2, 4, 1, 48, 46, 681, DateTimeKind.Utc).AddTicks(2198),
                            AssignedBy = "System",
                            RoleId = 7,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.AwardNoticeAuditLog", b =>
                {
                    b.HasOne("ZimbabweTenderAPI.Data.Entities.AwardNoticeEntity", "AwardNotice")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AwardNoticeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AwardNotice");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.ClosedTenderEntity", b =>
                {
                    b.HasOne("ZimbabweTenderAPI.Data.Entities.AwardNoticeEntity", "AwardNotice")
                        .WithMany("ClosedTenders")
                        .HasForeignKey("AwardNoticeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AwardNotice");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.ProcurementPlanAuditLog", b =>
                {
                    b.HasOne("ZimbabweTenderAPI.Data.Entities.ProcurementPlanEntity", "ProcurementPlan")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ProcurementPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProcurementPlan");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.ProcurementPlanItemEntity", b =>
                {
                    b.HasOne("ZimbabweTenderAPI.Data.Entities.ProcurementPlanEntity", "ProcurementPlan")
                        .WithMany("Items")
                        .HasForeignKey("ProcurementPlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProcurementPlan");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.TenderApprovalEntity", b =>
                {
                    b.HasOne("ZimbabweTenderAPI.Data.Entities.UserEntity", "ApproverUser")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZimbabweTenderAPI.Data.Entities.TenderApprovalEntity", "PreviousApproval")
                        .WithMany()
                        .HasForeignKey("PreviousApprovalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZimbabweTenderAPI.Data.Entities.UserEntity", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApproverUser");

                    b.Navigation("PreviousApproval");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.TenderAssignmentEntity", b =>
                {
                    b.HasOne("ZimbabweTenderAPI.Data.Entities.UserEntity", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZimbabweTenderAPI.Data.Entities.UserEntity", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("AssignedToUser");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.TenderAuditLog", b =>
                {
                    b.HasOne("ZimbabweTenderAPI.Data.Entities.ClosedTenderEntity", "ClosedTender")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ClosedTenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZimbabweTenderAPI.Data.Entities.LiveTenderEntity", "LiveTender")
                        .WithMany("AuditLogs")
                        .HasForeignKey("LiveTenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClosedTender");

                    b.Navigation("LiveTender");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.TenderChecklistItemEntity", b =>
                {
                    b.HasOne("ZimbabweTenderAPI.Data.Entities.UserEntity", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompletedByUser");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.TenderDocumentEntity", b =>
                {
                    b.HasOne("ZimbabweTenderAPI.Data.Entities.UserEntity", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.UserAuditLog", b =>
                {
                    b.HasOne("ZimbabweTenderAPI.Data.Entities.UserEntity", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("ZimbabweTenderAPI.Data.Entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZimbabweTenderAPI.Data.Entities.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.AwardNoticeEntity", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ClosedTenders");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.ClosedTenderEntity", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.LiveTenderEntity", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.ProcurementPlanEntity", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ZimbabweTenderAPI.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
